---
- name: Init Playbook
  hosts: ansible_test
  become: yes
  become_user: sudo

  tasks:
  - name: Install Packages
    ansible.builtin.package:
      name:
        - htop
        - wget
        - curl
      state: latest

  - name: Install Docker
    ansible.builtin.package:
      name:
        - docker.io
      state: latest
