---
- name: Setup Main Host
  hosts: ansible_test
  remote_user: vile

  tasks:
  - name: Install Main Stuff
    become: yes
    ansible.builtin.package:
      name: 
        - curl
        - wget
        - htop
      state: latest
  - name: Install Docker
    become: yes
    ansible.builtin.package:
      name:
        - docker.io
      state: latest
  - name: Install Ansible
    become: yes
    ansible.builtin.package:
      name: ansible
      state: latest
